name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    permissions: write
    runs-on: ubuntu-latest
    steps:
      - id: short_sha
        run: |
          echo "sha_short=${{GITHUB_SHA::}}" >> $GITHUB_ENV
